# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Product Detox by HellYeahItsMarvin.com
email:       'heaven@hellyeahitsmarvin.com'
description: 'Detox your product practice. A blog about intention, integrity and doing the right thing.'
baseurl:     '' # The subpath of your site, e.g. /blog - Important: Leading slash
url:         'https://product-detox.hellyeahitsmarvin.com' # The base hostname & protocol for your site without trailing slash
twitter:     ''
github:      ''
instagram:   ''
facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext